import path from "node:path";
import { fileURLToPath } from "node:url";

import { parseCloudflareWorkflowSource } from "../cloudflare/parseCloudflareWorkflowSource";
import { workflowToTimeline } from "../workflowToTimeline";
const workflowPath = process.argv[2];
if (!workflowPath) {
  throw new Error("Workflow path is required");
}
const rootNode = parseCloudflareWorkflowSource(workflowPath);
const timeline = workflowToTimeline(rootNode);
const baseName = path.basename(fileURLToPath(import.meta.url));
console.log(`// This file is auto-generated by ${baseName}`);
console.log(`// Do not edit directly. Edit the workflow instead.`);
console.log(`export const timeline = ${JSON.stringify(timeline, null, 2)};`);
