version: "3.8"

services:
  # --- Jaeger ---
  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686" # Jaeger UI
      - "14268:14268" # Jaeger HTTP ingest
      - "6831:6831/udp" # Jaeger UDP

  # --- Zipkin ---
  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:3.5.0
    ports:
      - "9411:9411" # Zipkin UI and API

volumes:
  clickhouse-data:
