direction: down

SoftwareSystemBankContainerAPIApplication: {
  label: "APIApplication"
}
SoftwareSystemBankContainerDatabase: {
  label: "Database"
}

SoftwareSystemBankContainerAPIApplication -> SoftwareSystemBankContainerDatabase: "readCredentials"
